export const runtime_prerequisites_in = ["runtime-prerequisites.in", `pip`];
export const runtime_prerequisites_txt = [
	"runtime-prerequisites.txt",
	`#
# This file is autogenerated by pip-compile with Python 3.13
# by the following command:
#
#    pip-compile --allow-unsafe --config=../.pip-tools.toml --output-file=runtime-prerequisites.txt --strip-extras runtime-prerequisites.in
#

# The following packages are considered to be unsafe in a requirements file:
pip==25.2
    # via -r runtime-prerequisites.in`,
];

export const runtime_in = [
	"runtime.in",
	`-c runtime-constraints.in  # limits known broken versions

# NOTE: v6.1 is needed to support metadata v2.4 including PEP 639
twine >= 6.1

# NOTE: Used to detect an ambient OIDC credential for OIDC publishing,
# NOTE: as well as PEP 740 attestations.
id ~= 1.0

# NOTE: This is pulled in transitively through \`twine\`, but we also declare
# NOTE: it explicitly here because \`oidc-exchange.py\` uses it.
# Ref: https://github.com/di/id
requests

# NOTE: Used to generate attestations.
pypi-attestations ~= 0.0.27
sigstore ~= 3.6.5

# NOTE: Used to detect the PyPI package name from the distribution files
packaging`,
];
export const runtime_txt = [
	"runtime.txt",
	`#
# This file is autogenerated by pip-compile with Python 3.13
# by the following command:
#
#    pip-compile --allow-unsafe --config=../.pip-tools.toml --output-file=runtime.txt --strip-extras runtime.in
#
annotated-types==0.7.0
    # via pydantic
betterproto==2.0.0b6
    # via sigstore-protobuf-specs
certifi==2025.8.3
    # via requests
cffi==1.17.1
    # via cryptography
charset-normalizer==3.4.3
    # via requests
cryptography==45.0.7
    # via
    #   pyopenssl
    #   pypi-attestations
    #   rfc3161-client
    #   secretstorage
    #   sigstore
dnspython==2.7.0
    # via email-validator
docutils==0.22
    # via readme-renderer
email-validator==2.3.0
    # via pydantic
grpclib==0.4.8
    # via betterproto
h2==4.3.0
    # via grpclib
hpack==4.1.0
    # via h2
hyperframe==6.1.0
    # via h2
id==1.5.0
    # via
    #   -r runtime.in
    #   sigstore
    #   twine
idna==3.10
    # via
    #   email-validator
    #   requests
jaraco-classes==3.4.0
    # via keyring
jaraco-context==6.0.1
    # via keyring
jaraco-functools==4.3.0
    # via keyring
jeepney==0.9.0
    # via
    #   keyring
    #   secretstorage
keyring==25.6.0
    # via twine
markdown-it-py==4.0.0
    # via rich
mdurl==0.1.2
    # via markdown-it-py
more-itertools==10.8.0
    # via
    #   jaraco-classes
    #   jaraco-functools
multidict==6.6.4
    # via grpclib
nh3==0.3.0
    # via readme-renderer
packaging==25.0
    # via
    #   -c runtime-constraints.in
    #   -r runtime.in
    #   pypi-attestations
    #   twine
platformdirs==4.4.0
    # via sigstore
pyasn1==0.6.1
    # via
    #   pypi-attestations
    #   sigstore
pycparser==2.22
    # via cffi
pydantic==2.11.7
    # via
    #   pypi-attestations
    #   sigstore
    #   sigstore-rekor-types
pydantic-core==2.33.2
    # via pydantic
pygments==2.19.2
    # via
    #   readme-renderer
    #   rich
pyjwt==2.10.1
    # via sigstore
pyopenssl==25.1.0
    # via sigstore
pypi-attestations==0.0.27
    # via -r runtime.in
python-dateutil==2.9.0.post0
    # via betterproto
readme-renderer==44.0
    # via twine
requests==2.32.5
    # via
    #   -r runtime.in
    #   id
    #   pypi-attestations
    #   requests-toolbelt
    #   sigstore
    #   twine
requests-toolbelt==1.0.0
    # via twine
rfc3161-client==1.0.4
    # via sigstore
rfc3986==2.0.0
    # via
    #   pypi-attestations
    #   twine
rfc8785==0.1.4
    # via sigstore
rich==14.1.0
    # via
    #   sigstore
    #   twine
secretstorage==3.3.3
    # via keyring
securesystemslib==1.3.0
    # via tuf
sigstore==3.6.5
    # via
    #   -r runtime.in
    #   pypi-attestations
sigstore-protobuf-specs==0.3.2
    # via
    #   pypi-attestations
    #   sigstore
sigstore-rekor-types==0.0.18
    # via sigstore
six==1.17.0
    # via python-dateutil
tuf==6.0.0
    # via sigstore
twine==6.1.0
    # via -r runtime.in
typing-extensions==4.15.0
    # via
    #   pydantic
    #   pydantic-core
    #   typing-inspection
typing-inspection==0.4.1
    # via pydantic
urllib3==2.5.0
    # via
    #   requests
    #   tuf
    #   twine`,
];

export const runtime_constraints_in = [
	"runtime-constraints.in",
	`###############################################################################
#                                                                             #
# This file is only meant to exclude broken dependency versions, not feature  #
# dependencies.                                                               #
#                                                                             #
# GUIDELINES:                                                                 #
#   1. Only list PyPI project versions that need to be excluded using \`!=\`    #
#      and \`<\`.                                                               #
#   2. It is allowed to have transitive dependency limitations in this file.  #
#   3. Apply bare minimum constraints under narrow conditions, use            #
#      environment markers if possible. E.g.  \`; python_version < "3.12"\`.    #
#   4. Whenever there are no constraints, let the file and this header        #
#      remain in Git.                                                         #
#                                                                             #
###############################################################################

# NOTE: Twine 6.1 needs packaging 24.2 to support metadata 2.4
# Ref: https://github.com/pypa/twine/pull/1180
packaging >= 24.2`,
];
