name: comment_pr
description: Creates or updates a comment on a pull request. Bespoke for gradio.
inputs:
  gh_token:
    description: "Your github token."
    required: true
  tag:
    description: "Fixed id for your comment."
    required: true
  message:
    description: "Message to comment."
    required: true
  additional_text:
    description: "Additional text to comment."
    required: false
  pr_number:
    description: "Pull request number."
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
